CREATE TABLE [dbo].[CustomerType]
(
	[Id] INT IDENTITY NOT NULL,
	[TypeName] NVARCHAR(100) NOT NULL,
	[Description] NVARCHAR(500) NULL,
	[CreatedAt] DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
	[CreatedBy] NVARCHAR(450) NOT NULL,
	CONSTRAINT PK_CustomerType_Id PRIMARY KEY ([Id]),
    CONSTRAINT FK_CustomerType_AspNetUsers_CreatedBy FOREIGN KEY ([CreatedBy]) REFERENCES [AspNetUsers]([Id]) ON DELETE NO ACTION
)
