CREATE TABLE [dbo].[JobTitle]
(
	[Id] INT NOT NULL IDENTITY,
	[TitleName] NVARCHAR(100) NOT NULL,
	[Description] NVARCHAR(500) NULL,
	[CreatedAt] DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
	[CreatedBy] NVARCHAR(450) NULL,
	CONSTRAINT PK_JobTitle_Id PRIMARY KEY ([Id]),
    CONSTRAINT FK_JobTitle_AspNetUsers_CreatedBy FOREIGN KEY ([CreatedBy]) REFERENCES [AspNetUsers]([Id]) ON DELETE SET NULL
)
